# Configuración para Netlify
[build]
  publish = "."
  command = ""

# Configuración para tipos MIME
[[headers]]
  for = "*.ts"
    [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "*.js"
    [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "*.css"
    [headers.values]
    Content-Type = "text/css; charset=utf-8"

# Configuración para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
